name: "API CI"

on:
  workflow_call:

jobs:
  build_client:
    name: "Build the Application"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: "Install Packages"
        working-directory: ./iot-mngmt-sys
        run: npm install

      # - name: "Lint"
      #   working-directory: ./iot-mngmt-sys
      #   run: npm run lint

      - name: "Build"
        working-directory: ./iot-mngmt-sys
        run: npm run build