name: DevSecOps Pipeline Orchestrator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # 1. Call API CI file
  call-api-ci:
    uses: ./.github/workflows/CI.yml # 👈 Path to your file
    secrets: inherit # Pass secrets down to the sub-workflow

  # 2. Call SAST file
  call-sast:
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  # 3. Call SCA file
  call-sca:
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  # 🚀 THE FINAL GATE: This job ONLY runs if all 3 'calls' above return success
  build-and-push-docker-image:
    needs: [call-api-ci, call-sast, call-sca] 
    uses: ./.github/workflows/cb.yml
    secrets: inherit

  # 4. Call Container Scan
  call-cs:
    uses: ./.github/workflows/cs.yml
    needs: build-and-push-docker-image
    secrets: inherit