name: DevSecOps Pipeline Orchestrator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # 1. Call API CI file
  call-api-ci:
    uses: ./CI.yml # 👈 Path to your file
    secrets: inherit # Pass secrets down to the sub-workflow

  # 2. Call SAST file
  call-sast:
    uses: ./SAST.yml
    secrets: inherit

  # 3. Call SCA file
  call-sca:
    uses: ./SCA.yml
    secrets: inherit

  # 🚀 THE FINAL GATE: This job ONLY runs if all 3 'calls' above return success
  build-and-push-docker-image:
    needs: [call-api-ci, call-sast, call-sca] 
    uses: ./CB.yml
    secrets: inherit

  # 4. Call Container Scan
  call-cs:
    uses: ./CS.yml
    needs: build-and-push-docker-image
    secrets: inherit